### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by Hikari-rom** [SecretHouseGame/ngx-design-system#23]
Ajout des différentes tailles d'icônes : 

### Tailles d'Icônes 

  - [ ] Taille L
  - [ ] Taille M 
  - [ ] Taille S

Pour référence : 

![image](https://user-images.githubusercontent.com/58610934/168846968-e3329530-beea-4175-a282-0b90694153e3.png)

**Comment by Arty3P** [comment]
Pas besoin
